Add 404
ioos/ioosngdac pull request #203
Opened 2023-08-14 12:49 UTC by ocefpaf

@kbailey-noaa and @MathewBiddle this PR removes all the pages in the gh-pages here, sets a 404 page, and a redirect to the new one for the landing page. The redirect is set only to the main landing page, so folks with a direct link to a sub-page will get the 404 instead.

PS: This whole branch, with its history, is available in the https://ioos.github.io/glider-dac gh-pages now.

2023-08-14 13:21 UTC, ocefpaf commented on index.html
> +		you'll be redirected to IOOS CodeLab
Ooops. Fixed that in the next commit.

2023-08-14 13:34 UTC, MathewBiddle commented on index.html
> +		you'll be redirected to IOOS CodeLab
thx!

2023-08-14 13:35 UTC, MathewBiddle commented
LGTM. @kbailey-noaa should have final say before we merge this in.

2023-08-14 19:53 UTC, kbailey-noaa requested changes
index.html changes -- the <body> section mentions IOOD CodeLab.

2023-08-14 20:01 UTC, MathewBiddle commented on index.html
> +		IOOS CodeLab
IOOS Glider DAC

2023-08-14 22:51 UTC, ocefpaf commented
> index.html changes -- the section mentions IOOS CodeLab.

Should be OK in the last commit.

2023-08-15 14:08 UTC, MathewBiddle commented
LGTM! Thanks @ocefpaf!

2023-08-15 15:07 UTC, kbailey-noaa approved these changes

2023-08-15 15:07 UTC, merged